name: Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: false

      - name: login to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > ~/.npmrc
          git config --global user.name "ariesclark"
          npm whoami
      - name: install dependencies
        run: pnpm i

      - name: build package
        run: pnpm build:source
      
      - name: publish package
        run: pnpm publish --no-git-checks --access public

      - name: build documentation
        run: pnpm build:documentation

      - name: publish documentation
        run: |
          cp -r docs/ /tmp/docs
          git checkout pages
          rm * -rf
          cp /tmp/docs/* .
          git add *
          git commit -m "chore(build): generate documentation"
          git push --force